### ISSUE TITLE
[Ranking] Idioma al enviar puntaje

### ISSUE THREAD

**Issue by pablolivera** [Grupo6PIS/BeatIt-WPhone#25]
Celular en inglés y muestra mensaje en español.
"Puntaje enviado con éxito" (Lo que está en español le falta el tilde)

![wp_ss_20141014_0002_2](https://cloud.githubusercontent.com/assets/8220382/4639284/d3adecf8-5409-11e4-94e0-1a3e65560482.png)

**Comment by MBerguer** [comment]
Pronto [commit 98]
