### ISSUE TITLE
[Wake Me Up] Forma de juego de cada intento

### ISSUE THREAD

**Issue by pablolivera** [Grupo6PIS/BeatIt-WPhone#26]
Al jugar cada intento de agitar debe ser independiente de los demás.
Además cada cuenta atrás debe comenzar en 10.
Ejemplo: Si pierdo en el segundo agite debo poder agitar una tercera en el mismo intento.

**Comment by cristianbauza** [comment]
@pablolivera O sea que en el nivel avanzado que el mas difsil son 9 segundos sin ver el teimpo, el jugador veria el 10 ... y se le desaparece? a mi me parece que siempre para todos los intentos deveria mostrar el cronometro por lo menos 3 o 4 segundos. 

En cuanto a lo de que cada intento es independiente yo lo interprete mal de la especificacion del desafio:
"El Usuario deberá agitar el celular cuando la cuenta llegue a 0 segundos. El desafío consistirá en realizar lo pedido X cantidad de veces. Se mostrará la cuenta regresiva y cuando resten Y segundos se ocultará, el tiempo Y aumentará en cada repetición. 
Si el Usuario agita el celular antes de que finalice la cuenta regresiva o después (con una tolerancia de medio segundo) se tomará como fallido."

Cuando dice se tomara como fallido interprete el desafio.

**Comment by aleb89** [comment]
Cristian,

En todas las repeticiones, el contador debe empezar en 10 segundos. Siempre.
En el nivel Básico se oculta a partir de los 3, 4 y 5 segundos. Pero siempre comenzando en 10.
En el nivel Avanzado se oculta a partir de los 3, 5, 7 y 9 segundos. Pero siempre comenzando en 10.

En la última repetición del nivel Avanzado, sólo se muestra 1 segundo el 10, y después se oculta el contador.

Otra cosa, para ganar en cada repetición (y por lo tanto, tener un "success"/éxito) el tipo tiene que frenar el contador entre +0,5 y -0,5 segundos. O sea, hay medio segundo de tolerancia de más y de menos. Por lo tanto, contamos como exitoso si lo frena entre los 9,5 segundos y los 10,5.

**Comment by cristianbauza** [comment]
Yo siempre le daba un tiempo de gracia para ver el cronometro, pero ya quedo arreglado, parte desde dies segun las especificaciones que me dieron por aqui.
