### ISSUE TITLE
[Wake Me Up] Error en cantidad de intentos

### ISSUE THREAD

**Issue by pablolivera** [Grupo6PIS/BeatIt-WPhone#27]
Jugando algunas veces me mostró lo 4/3 en attemps.
Sólo una vez me ocurrió, denle una mirada que puede estar ocurriendo.

![wp_ss_20141014_0004](https://cloud.githubusercontent.com/assets/8220382/4639340/371ba66c-540b-11e4-92a9-1b3c32c3ba4c.png)

**Comment by cristianbauza** [comment]
Realice un cambio en el codigo, algo mas bien preventivo, pero la verdad no puedo reproducir el error.
Si alguien tiene un procedimiento para que le suceda el error. avise.
