### ISSUE TITLE
Ver el Mensaje Whake Me Up!

### ISSUE THREAD

**Issue by cristianbauza** [Grupo6PIS/BeatIt-WPhone#30]
Marcelo planteo cambiar Wake Me Up! Por Share me Up!, seguro se confundio con Shake me Up, confirmar esto, y en caso positivo, ver que se va a poner en la verción español.

**Comment by aleb89** [comment]
Si es por lo que mandó en el mail, no queda nada claro.
Mientras tanto, yo lo dejaría como está (porque además implica renombrar todas las clases, etc etc)

**Comment by MBerguer** [comment]
Queda como está
