### ISSUE TITLE
Agregar los niveles en los desafios

### ISSUE THREAD

**Issue by goja288** [Grupo6PIS/BeatIt-WPhone#33]

**Comment by malayonoyarbide** [comment]
En donde se debería agregar el nivel?

**Comment by MBerguer** [comment]
Lo que está quedando es el desafío 10 que venga desde el servidor

**Comment by MBerguer** [comment]
Continúa en esta issue:
https://github.com/Grupo6PIS/BeatIt-WPhone/issues/35
