### ISSUE TITLE
Wake Me Up! - Descripción cortada y mensaje de finalizado

### ISSUE THREAD

**Issue by pablolivera** [Grupo6PIS/BeatIt-WPhone#41]
Description se muestra cortada en la última linea - Ver captura.

Al jugar el último intento e ir a "atrás" luego el mensaje aparece en otra pantalla. - Ver 2da captura.

![wp_ss_20141020_0001](https://cloud.githubusercontent.com/assets/8220382/4730480/99662790-599a-11e4-9b7a-d574d41e04e5.png)

![wp_ss_20141021_0001](https://cloud.githubusercontent.com/assets/8220382/4730481/99689390-599a-11e4-885b-acc77e9af6b0.png)

**Comment by MBerguer** [comment]
Lo primero ya lo arreglé, lo otro no..

**Comment by cristianbauza** [comment]
Solucionado, lo del mensaje lo saque ya que por lo que vi en los otros desafios no se pone nigun mensaje al finalizar los mismos.
