### ISSUE TITLE
En SongComplete, se corta la canción actual y comienza la anterior

### ISSUE THREAD

**Issue by goja288** [Grupo6PIS/BeatIt-WPhone#42]
Es un error aleatorio por eso la dificultad de reproducirlo, sin embargo paso muchas veces que si se selecciona rapidamente la opción en las primeras dos canciones, ya en la tercera cuando va 1/3 de la canción actual, empieza a correr la otra

**Comment by malayonoyarbide** [comment]
No lo he podido reproducir. 
Necesito el paso a paso mas detallado.

**Comment by MBerguer** [comment]
Error irreproducible,
Igual, funciona bien por ahora, cualquier cosa se re-abre..
