### ISSUE TITLE
[Desafio Selfie Group] UI varios

### ISSUE THREAD

**Issue by malayonoyarbide** [Grupo6PIS/BeatIt-WPhone#51]
El titulo del desafio en español se ve cortado.
No se están mostrando los datos del detalle del desafío.
Cuando se envia la foto debería aparecer como deshabitado el botón de comenzar.
Quitar el MessageBox que se muestra indicando la cantidad de caras que se detecto.

**Comment by MBerguer** [comment]
La cantidad de personas que detectó esta bueno, mas que nada por el tema de que puede fallar...
Lo otro ya está arreglado
