### ISSUE TITLE
[Desafio Wake Me Up] Boton atras

### ISSUE THREAD

**Issue by malayonoyarbide** [Grupo6PIS/BeatIt-WPhone#56]
Cuando se inicia el desafío y se presiona el botón de atrás, pareciera que sigue corriendo el desafío. Ya que se escuchan los sonidos y de repente la aplicación navega al detalle del desafío.

**Comment by malayonoyarbide** [comment]
Por este error se esta mostrando mal la cantidad de intentos y muestra por ejemplo 5/3 intentos.

**Comment by cristianbauza** [comment]
@malayonoyarbide Martin, lo de que se escuchara el sonido al ir atras no me pasaba, si lo de 5/3 por ejemplo. creo que lo solucione, cualquier cosa avisen.
