### ISSUE TITLE
[Selfie Groupie] Titulo y description

### ISSUE THREAD

**Issue by pablolivera** [Grupo6PIS/BeatIt-WPhone#60]
Cambiar el titulo en español a Selfie Groupie.

**En inglés**
"more, Remember" cambiar coma por punto.
"you should" cambiar por "you have to". 
"two or more" agregar "people" ===> "**two or more people**"
"remember that more people" cambiar por "remember that more faces in the pictures".

**Comment by MBerguer** [comment]
Pronto!
