### ISSUE TITLE
Ranking - Funcionamiento del envío de puntajes

### ISSUE THREAD

**Issue by MBerguer** [Grupo6PIS/BeatIt-WPhone#72]
Enviar puntaje solo cuando se completen todos los desafíos.
Osea, eliminar el botón de enviar puntaje.

Funcionamiento:
Únicamente se deberán enviar puntajes luego de que la persona jugó por lo menos 1 vez a cada desafío (todos los desafíos deben tener el tick),
Luego de esto, cada nuevo intento realizado por el usuario, se debe enviar puntaje al servidor (si el puntaje obtenido en este nuevo intento es mayor, osea que la suma total también ser;a mayor).
De esta forma se mantiene actualizado el ranking

**Comment by MBerguer** [comment]
@malayonoyarbide  lo damos como finalizado?

**Comment by malayonoyarbide** [comment]
Lo pruebo un poco mas y lo cierro.
